twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : cmd_vel
        timeout : 0.5
        priority: 10
      keyboard:
        topic   : cmd_vel_tracker
        timeout : 0.5
        priority: 20
      joy:
        topic   : cmd_vel_joy
        timeout : 0.5
        priority: 30
      walk:
        topic   : cmd_vel_walk
        timeout : 0.5
        priority: 40
      rand:
        topic   : cmd_vel_rand
        timeout : 0.5
        priority: 50
